"""
Strategy registry (spec section 24): the standardized metadata every
later layer filters on -- family, direction, timeframes, ticker scope,
session, data requirements.

Loaded from catalog/strategies.json (generated by
tools/strategy_engine/build_catalog.py, then edited by hand if needed).
The catalog's `version` is logged with every selection decision.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from app.strategy_engine.models import (
    AssetScope,
    Direction,
    Family,
    MinimumData,
    Session,
    StrategyMeta,
    Timeframe,
)

CATALOG_PATH = Path(__file__).resolve().parent / "catalog" / "strategies.json"


class CatalogError(ValueError):
    pass


def _parse(entry: dict) -> StrategyMeta:
    try:
        tickers = tuple(t.upper() for t in entry.get("allowed_tickers") or ())
        scope = AssetScope(entry["asset_scope"])
        if scope is AssetScope.SPECIFIC_TICKER and not tickers:
            raise CatalogError(f"{entry['slug']}: SPECIFIC_TICKER needs allowed_tickers")
        timeframes = tuple(Timeframe.parse(t) for t in entry["timeframes"])
        if not timeframes:
            raise CatalogError(f"{entry['slug']}: at least one timeframe is required")
        return StrategyMeta(
            id=int(entry["id"]),
            slug=entry["slug"],
            name=entry["name"],
            family=Family(entry["family"]),
            secondary_families=tuple(Family(f) for f in entry.get("secondary_families") or ()),
            direction=Direction(entry["direction"]),
            timeframes=timeframes,
            asset_scope=scope,
            allowed_tickers=tickers,
            session=Session(entry["session"]),
            minimum_data=MinimumData(entry["minimum_data"]),
            uses_premarket=bool(entry.get("uses_premarket", False)),
            requires_premarket_data=bool(entry.get("requires_premarket_data", False)),
            requires_event_data=bool(entry.get("requires_event_data", False)),
            runnable=bool(entry.get("runnable", True)),
            not_runnable_reason=entry.get("not_runnable_reason", ""),
            source=entry.get("source", ""),
            classification=dict(entry.get("classification") or {}),
        )
    except (KeyError, ValueError) as exc:
        if isinstance(exc, CatalogError):
            raise
        raise CatalogError(f"invalid catalog entry {entry.get('slug', entry)!r}: {exc}") from exc


class StrategyRegistry:
    def __init__(self, strategies: list[StrategyMeta], version: str):
        self.version = version
        self._by_id: dict[int, StrategyMeta] = {}
        self._by_slug: dict[str, StrategyMeta] = {}
        for s in strategies:
            if s.id in self._by_id:
                raise CatalogError(f"duplicate strategy id {s.id}")
            if s.slug in self._by_slug:
                raise CatalogError(f"duplicate strategy slug {s.slug}")
            self._by_id[s.id] = s
            self._by_slug[s.slug] = s

    @classmethod
    def from_file(cls, path: Path = CATALOG_PATH) -> "StrategyRegistry":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls([_parse(e) for e in data["strategies"]], version=str(data.get("version", "unversioned")))

    def all(self) -> list[StrategyMeta]:
        return sorted(self._by_id.values(), key=lambda s: s.id)

    def get(self, key: int | str) -> StrategyMeta:
        found = self._by_id.get(key) if isinstance(key, int) else self._by_slug.get(key)
        if found is None:
            raise KeyError(f"unknown strategy {key!r}")
        return found

    def __len__(self) -> int:
        return len(self._by_id)


@lru_cache(maxsize=1)
def default_registry() -> StrategyRegistry:
    return StrategyRegistry.from_file()
